"""add remember_me column in sessions table

Revision ID: 8b72a1ed19c1
Revises: c12a46b65e6f
Create Date: 2026-07-06 23:41:29.309874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b72a1ed19c1"
down_revision: str | Sequence[str] | None = "c12a46b65e6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_sessions", sa.Column("remember_me", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_sessions", "remember_me")
    # ### end Alembic commands ###
