"""migrate to postgresql, add session table

Revision ID: c12a46b65e6f
Revises: 8a1ff1b1cd0d
Create Date: 2026-07-06 18:08:12.683542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c12a46b65e6f"
down_revision: str | Sequence[str] | None = "8a1ff1b1cd0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token_hash"),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.add_column("requests", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_requests_creator_id"), "requests", ["creator_id"], unique=False)
    op.create_foreign_key(None, "requests", "users", ["creator_id"], ["id"], ondelete="RESTRICT")
    op.add_column("users", sa.Column("email", sa.Text(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("admin", "user", name="user_role", native_enum=False, length=20),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("first_name", sa.String(length=80), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=80), nullable=True))
    op.add_column("users", sa.Column("middle_name", sa.String(length=80), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(length=32), nullable=True))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.drop_column("users", "blocked_at")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "is_verified")
    op.drop_column("users", "is_active")
    op.drop_column("users", "phone")
    op.drop_column("users", "middle_name")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "role")
    op.drop_column("users", "email")
    op.drop_constraint("fk_requests_creator_id_users", "requests", type_="foreignkey")
    op.drop_index(op.f("ix_requests_creator_id"), table_name="requests")
    op.drop_column("requests", "creator_id")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
